# Linear Algebra

## 3. Matrices

### 3.1 Matrix definition



$$\mathbf{B} = 
    \begin{bmatrix} 
        1 & 2 & 0 & 1\\
        4 & 6 &-1 & 0\\
        -2& \sqrt{2} & 0 & -0.5\\
     \end{bmatrix}
$$



<div class="alert alert-block alert-info">
    A <b>matrix $\mathbf{A}$</b> of dimension $m\times n$ has $m$ rows and $n$ columns and is represented as:
    $$
    \mathbf{A} = 
    \begin{bmatrix}
        a_{1,1} & a_{1,2} & \cdots & a_{1,n}\\
        a_{2,1} & a_{2,2} & \cdots & a_{2,n}\\
        \vdots &\vdots & \ddots & \vdots\\
        a_{m,1} & a_{m,2} & \cdots & a_{m,n}\\
    \end{bmatrix}
    $$
</div>

---

### 3.3 Matrix operations: multiplication by scalar and addition

#### 3.3.1 Multiplying a matrix by a scalar


$$
2\cdot
\begin{bmatrix}
    0 & 1 & 0\\
    -1 & 0.5 & 2
\end{bmatrix}
=
\begin{bmatrix}
    2\times 0 & 2\times 1 & 2\times 0\\
    2\times -1 & 2\times 0.5 & 2\times 2
\end{bmatrix}
=
\begin{bmatrix}
    0 & 2 & 0\\
    -2 & 1 & 4
\end{bmatrix}
$$

#### 3.3.2 Addition and subtraction



Let's add matrices $\mathbf{A} = \begin{bmatrix}1&-1\\0&2\\-0.5&1\end{bmatrix}$ and $\mathbf{B} = \begin{bmatrix}0.2&-2\\-3&1\\5&2\end{bmatrix}$.


$
\mathbf{A}
+
\mathbf{B} =
\begin{bmatrix}
    1 + 0.2 & -1 + (-2)\\
    0 + (-3) & 2 + 1\\
    -0.5 + 5 & 1 + 2
\end{bmatrix} =
\begin{bmatrix}
    1.2 & -3\\
    -3 & 3\\
    4.5 & 3
\end{bmatrix}
$



#### 3.3.3 Properties of matrix addition and multiplication by scalars

Similarly to vectors, we have the following properties:

$\;\;\text{1. }\;\; \mathbf{A} + \mathbf{B} = \mathbf{B} + \mathbf{A}\;\;$ (**commutativity**)

$\;\;\text{2. }\;\; \mathbf{A} + \mathbf{O} = \mathbf{A}$

$\;\;\text{3. }\;\; c\left(\mathbf{A} + \mathbf{B}\right) = c\mathbf{A} + c\mathbf{B},\hspace{.2cm} c\in \mathbb{R}$ (**distributivity of a scalar**)

$\;\;\text{4. }\;\; \left(cd\right)\mathbf{A} = c\left(d\mathbf{A}\right)$

$\;\;\text{5. }\;\; \mathbf{A} + (\mathbf{B} + \mathbf{C}) = (\mathbf{A} + \mathbf{B}) + \mathbf{C}\;\;$ (**associativity**)

$\;\;\text{6. }\;\; \mathbf{A} + (-\mathbf{A}) = \mathbf{O}$

$\;\;\text{7. }\;\; (c + d) \mathbf{A} = c \mathbf{A} + d \mathbf{A}$

where $\mathbf{O}$ is the zero matrix, and $c$ and $d$ are scalars.

Let's check some of the properties of the matrix transpose:

$\;\;\text{1. }\;\; (\mathbf{A}+\mathbf{B})^T = \mathbf{A}^T+\mathbf{B}^T$

$\;\;\text{2. }\;\ (c\mathbf{A})^T = c\mathbf{A}^T$

$\;\;\text{3. }\;\; \mathbf{A}$ is symmetric if and only if $\mathbf{\mathbf{A}} = \mathbf{A}^T$.

---

## 4. NumPy arrays and matrices

### 4.2 Matrices and linear algebra using NumPy

#### 4.2.2 Matrix operations

**Multiplication by a scalar**

Let's bring back our matrix `B`:

In [6]:
print("Matrix B:")
print(B)

Matrix B:
[[-2 -2  1]
 [ 0  1  1]]


To multiply a matrix (2D array) by a scalar, we simply use the Python multiplication operator `*`:

In [7]:
0.5 * B  # simply use the Python multiplication operator *

array([[-1. , -1. ,  0.5],
       [ 0. ,  0.5,  0.5]])

**Addition (and subtraction) of matrices**

Let's bring back our matrices `A` and `B`:

In [8]:
print("Matrix A:\n", A, "\n")
print("Matrix B:\n", B)

Matrix A:
 [[ 2.          0.1        -1.        ]
 [ 3.          0.2         1.41421356]] 

Matrix B:
 [[-2 -2  1]
 [ 0  1  1]]


To add two matrices (2D arrays) together, we can use Python addition operator `+`, which adds the matrices element-wise:

In [9]:
A + B  # simply use the Python addition operator +

array([[ 0.        , -1.9       ,  0.        ],
       [ 3.        ,  1.2       ,  2.41421356]])

We can do the same for subtraction, using `-`:

In [10]:
A - B  # simply use the Python subtraction operator -

array([[ 4.        ,  2.1       , -2.        ],
       [ 3.        , -0.8       ,  0.41421356]])

#### 4.3.3 Concatenation

We can concatenate numpy arrays along rows or columns, given that their dimensions are compatible:

In [36]:
# create arrays of shape (2, 3)
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

Matrix A:
 [[1 2 3]
 [4 5 6]]
Matrix B:
 [[ 7  8  9]
 [10 11 12]]


In [37]:
np.concatenate((A, B), axis = 0)  # concatenate along axis 0 (rows)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [38]:
np.concatenate((A, B), axis = 1)  # concatenate along axis 1 (columns)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

#### 4.3.4 Iterating through arrays

You can iterate through the rows of a matrix (2D array):

In [39]:
a = np.array([[.0, .2, .4], [.6, .8, 1.]])
i = 1
for row in a:
    print(f"row {i}: {row}")
    i+=1

row 1: [0.  0.2 0.4]
row 2: [0.6 0.8 1. ]


---

<img src="./media/enough_is_enough.gif"/>

---